apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-02-17T19:30:41Z"
  generation: 1
  labels:
    run: newtest
  name: newtest
  namespace: default
  resourceVersion: "713575"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/newtest
  uid: fc1f8bd6-51bb-11ea-bbdd-0210153c6438
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: newtest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: newtest
    spec:
      containers:
      - image: nmour92/newnginx
        imagePullPolicy: Always
        name: newtest
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-02-17T19:30:44Z"
    lastUpdateTime: "2020-02-17T19:30:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-02-17T19:30:41Z"
    lastUpdateTime: "2020-02-17T19:30:44Z"
    message: ReplicaSet "newtest-55d948fc9b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
